import { MappingSpec, MappingRule, GeneratedArtifact, TransformationDef } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// XSLT 1.0 Generator for SAP CPI  (XML → XML mappings)
// SAP CPI supports XSLT 1.0 and 2.0; this generates XSLT 1.0 for broad support
// ─────────────────────────────────────────────────────────────────────────────

function xpathFromPath(path: string): string {
  return path
    .split('.')
    .map((seg) => seg.replace(/\[\]$/, ''))
    .join('/');
}

function renderXsltValue(rule: MappingRule, transform?: TransformationDef): string {
  const primary = rule.sourcePaths[0];
  const xpath = xpathFromPath(primary);

  if (!transform || transform.type === 'direct') {
    return `<xsl:value-of select="${xpath}"/>`;
  }

  const p = transform.params ?? {};
  switch (transform.type) {
    case 'constant':
      return `<xsl:text>${p['value'] ?? ''}</xsl:text>`;
    case 'upper_case':
      return `<xsl:value-of select="translate(${xpath}, 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/>`;
    case 'lower_case':
      return `<xsl:value-of select="translate(${xpath}, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"/>`;
    case 'concat': {
      const fields = (p['fields'] ?? '').split(',').map((f) => f.trim());
      const sep = p['separator'] ?? '';
      const concatArgs = fields
        .map((f) => xpathFromPath(f))
        .join(`, '${sep}', `);
      return `<xsl:value-of select="concat(${concatArgs})"/>`;
    }
    case 'conditional': {
      const testXpath = xpathFromPath(primary);
      const ifTrue = p['ifTrue'] ?? `<xsl:value-of select="${testXpath}"/>`;
      const ifFalse = p['ifFalse'] ?? '';
      return `<xsl:choose>
          <xsl:when test="${testXpath} != ''">
            ${ifTrue}
          </xsl:when>
          <xsl:otherwise>${ifFalse}</xsl:otherwise>
        </xsl:choose>`;
    }
    default:
      return `<xsl:value-of select="${xpath}"/>`;
  }
}

function buildXsltRules(rules: MappingRule[], rootSource: string): string {
  const grouped = new Map<string, MappingRule[]>();

  for (const rule of rules) {
    const parts = rule.targetPath.split('.');
    const parentKey = parts.length > 1 ? parts.slice(0, -1).join('.') : '__root__';
    if (!grouped.has(parentKey)) grouped.set(parentKey, []);
    grouped.get(parentKey)!.push(rule);
  }

  const lines: string[] = [];
  const processed = new Set<string>();

  function renderGroup(parentPath: string, indent: string): void {
    const groupRules = grouped.get(parentPath) ?? [];
    for (const rule of groupRules) {
      const targetLeaf = rule.targetPath.split('.').pop() ?? rule.targetPath;
      const childPath = rule.targetPath;
      const hasChildren = grouped.has(childPath);

      if (hasChildren && !processed.has(childPath)) {
        processed.add(childPath);
        lines.push(`${indent}<${targetLeaf}>`);
        renderGroup(childPath, indent + '  ');
        lines.push(`${indent}</${targetLeaf}>`);
      } else {
        lines.push(`${indent}<${targetLeaf}>`);
        lines.push(`${indent}  ${renderXsltValue(rule, rule.transformation)}`);
        lines.push(`${indent}</${targetLeaf}>`);
      }
    }
  }

  renderGroup('__root__', '          ');
  return lines.join('\n');
}

export function generateXslt(spec: MappingSpec): GeneratedArtifact {
  if (spec.sourceFormat !== 'XML' || spec.targetFormat !== 'XML') {
    return {
      type: 'XSLT',
      filename: `${spec.name.replace(/\s+/g, '_')}_mapping.xslt`,
      content: '<!-- XSLT generation is only supported for XML→XML mappings -->',
    };
  }

  const sourceRoot = spec.sourceSchema[0]?.path?.split('.')[0] ?? 'root';
  const targetRoot = spec.targetSchema[0]?.path?.split('.')[0] ?? 'targetRoot';
  const rulesContent = buildXsltRules(spec.rules, sourceRoot);

  const content = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="xml" indent="yes" encoding="UTF-8"/>

  <!-- Generated by CPI Mapping Copilot for mapping: ${spec.name} -->

  <xsl:template match="/${sourceRoot}">
    <${targetRoot}>
${rulesContent}
    </${targetRoot}>
  </xsl:template>

  <xsl:template match="@* | node()">
    <xsl:copy>
      <xsl:apply-templates select="@* | node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>`;

  return {
    type: 'XSLT',
    filename: `${spec.name.replace(/\s+/g, '_')}_mapping.xslt`,
    content,
  };
}
